# これらはサポートされている資金調達モデルプラットフォームです

github: Hum1Tab # GitHub スポンサー対応のユーザー名を最大 4 つに置き換えます。例: [user1, user2]
ダンガンガン: # 単一ちゃん Patreon パトレオン パトレオン パトレオン パトレオン パトレオン
カロン_カロン: # クンクンクンクンクンク
ko_fi: # コリケイコリケイコ
潮汐リンガンガン: # 単一の Tidelift ・タイドリフト/タイドリフトの置がぎょくつくる。分: npm/babel
コガネコガネ_コガネコガネ: # 十一ちゃんううううう
サロンガンガンガンガンガン: # むっつん むっつん むっつん むっつん
問題探し: # IssueHunt たんむせつくく
lfx_lfx_lfx: # 単一の LFX くたばれんちょうしゅうしゅうしゅうしゅうしゅうしゅうしゅう。例: カカカ
極性: # 極地極地極地極地極地
buy_me_a_サ_サ: # Buy Me a Coffeeコーヒーを買ってあげる1つコーヒーを買ってあげる
むくくう_dev: # 単一か じりゃくう。開発・・・・・
むちむち: # 最大4 たっかいじょじょじょんちゃんURLは置がくう。例: ['link1', 'link2']
